"""Add salary_range to applications

Revision ID: 3d91ab33354d
Revises: 355d42e15861
Create Date: 2026-02-17 20:28:47.088535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d91ab33354d'
down_revision: Union[str, Sequence[str], None] = '355d42e15861'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('salary_range', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'salary_range')
    # ### end Alembic commands ###
